#!/bin/bash

run_brew() {

    # Check for Homebrew
    if type_exists 'brew'; then
        e_header "Checking status of desired Homebrew formulae..."
        local list_formulae
        local -a missing_formulae
        local -a desired_formulae=(
            'coreutils' # GNU core utilities (those that come with OS X are outdated)
            'tree'
            'wget'
            'git'
            'bash-completion'
            'htop'
            'cmake'
        )

        for index in ${!desired_formulae[*]}
        do
            if ! formula_exists ${desired_formulae[$index]}; then
                # Store the name (and options) of every missing formula
                e_header "Installing missing ${desired_formulae[$index]}..."
                brew install ${desired_formulae[$index]}
                [[ $? -eq 0 ]] && e_success "Done"
            fi
        done

        # Support installing applications that are distributed as binaries.
        brew list --cask sourcetree &>/dev/null || brew install --cask sourcetree


        # Remove outdated versions from the Cellar
        brew cleanup
    else
        printf "\n"
        e_error "Error: Homebrew not found."
        printf "Aborting...\n"
        exit
    fi

}
