#!/bin/bash

run_brew() {

    # Check for Homebrew
    if type_exists 'brew'; then
        e_header "Checking status of desired Homebrew formulae..."
        local list_formulae
        local -a missing_formulae
        local -a desired_formulae=(
            'coreutils' # GNU core utilities (those that come with OS X are outdated)
            'tree'
            'wget --enable-iri'
            'git'
            'bash-completion'
            'htop-osx'
            'cmake'
            'caskroom/cask/brew-cask'
        )

        for index in ${!desired_formulae[*]}
        do
            if ! formula_exists ${desired_formulae[$index]}; then
                # Store the name (and options) of every missing formula
                e_header "Installing missing ${desired_formulae[$index]}..."
                brew install ${desired_formulae[$index]}
                [[ $? ]] && e_success "Done"
            fi
        done


        # Uninstall previous versions to make sure we're using --HEAD

        #if formula_exists "ruby-install"; then brew uninstall ruby-install; fi
        #brew install ruby-install --HEAD

        #if formula_exists "chruby"; then brew uninstall chruby; fi
        #brew install chruby --HEAD

        #if formula_exists "gem_home"; then brew uninstall gem_home; fi
        #brew install --HEAD https://raw.github.com/postmodern/gem_home/master/homebrew/gem_home.rb

        # Support installing applications that are distributed as binaries.
        brew cask install sourcetree
        
        # Remove outdated versions from the Cellar
        brew cleanup
    else
        printf "\n"
        e_error "Error: Homebrew not found."
        printf "Aborting...\n"
        exit
    fi

}
