#!/bin/bash

# bash_aliases

# Allow aliases to be with sudo
alias sudo="sudo "

# Easier navigation: .., ..., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ~="cd ~"
alias -- -="cd -"

alias m1st="mvn install -T1C -DskipTests"
alias mist="mvn install -DskipTests"
alias m1t="mvn test -T1C"
alias m1vv="mvn verify -T1C"
alias mvv="mvn verify"
alias m1st="mvn test -T1C -DskipTests"
alias m1cst="mvn clean install -T1C -DskipTests"
alias m1c="mvn clean install -T1C"
alias m1="mvn install -T1C"
alias mci="mvn clean install"
alias mdls="mvn dependency:list"
alias mdt="mvn dependency:tree"

alias bi="bundle install"
alias bu="bundle update"
alias be="bundle exec"

alias gp="git pull"
alias gfu="git fetch upstream"
alias gru="git rebase upstream/master"

alias gmu="git merge upstream/master"
alias gmf="git merge --ff-only"
alias gma="git merge --abort"

alias gri="git rebase --interactive"
alias gra="git rebase --abort"
alias grc="git rebase --continue"
alias gcpc="git cp --continue"
alias gcp="git cp"
alias gcpa="git cp --abort"

alias tower="gittower ."

alias sdr="cd ${HOME}/git/data/spring-data-redis"
alias sdm="cd ${HOME}/git/data/spring-data-mongodb"
alias sdc="cd ${HOME}/git/data/spring-data-cassandra"
alias sdb="cd ${HOME}/git/data/spring-data-build"
alias sdj="cd ${HOME}/git/data/spring-data-jdbc"
alias sv="cd ${HOME}/git/spring/spring-vault"
alias scv="cd ${HOME}/git/cloud/spring-cloud-vault"
alias scvs="cd ${HOME}/git/cloud/spring-cloud-vault-config-samples"
alias lettuce="cd ${HOME}/git/me/lettuce"
alias spinach="cd ${HOME}/git/me/spinach"

importprfunction() {
    curl -L ${1}.patch | git am --ignore-whitespace
}

changeMac() {
  local mac=$(openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//')
  sudo ifconfig en0 ether $mac
  sudo ifconfig en0 down
  sudo ifconfig en0 up
  echo "Your new physical address is $mac"
}

alias importpr=importprfunction
alias cass-3="cd /Users/Shared//Entwicklung/tools/apache-cassandra-3.11.2/bin"
alias cass-4="cd /Users/Shared//Entwicklung/tools/apache-cassandra-4.0.0/bin"

# List dir contents aliases
# ref: http://ss64.com/osx/ls.html
# Long form no user group, color
alias l="ls -oG"
# Order by last modified, long form no user group, color
alias lt="ls -toG"
# List all except . and ..., color, mark file types, long form no user group, file size
alias la="ls -AGFoh"
# List all except . and ..., color, mark file types, long form no use group, order by last modified, file size
alias lat="ls -AGFoth"

# MCS search
alias ms="mcs search"

# Concatenate and print content of files (add line numbers)
alias catn="cat -n"

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en1"

# Copy my public key to the pasteboard
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | printf '=> Public key copied to pasteboard.\n'"

# Flush DNS cache
alias flushdns="dscacheutil -flushcache"

# Empty the Trash on all mounted volumes and the main HDD
# Also, clear Apple’s System Logs to improve shell startup speed
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

# Show/hide hidden files in Finder
alias showdotfiles="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidedotfiles="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting)
alias showdeskicons="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
alias hidedeskicons="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
