# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"
DEFAULT_USER=mpaluch

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

export DOTFILES=$HOME/.dotfiles
export ZSH=$HOME/.oh-my-zsh
# User configuration

if [[ -f "$DOTFILES/zsh/zsh_options" ]]; then
    source $DOTFILES/zsh/zsh_options
fi

if [[ -f "$DOTFILES/devtools" ]]; then
    source $DOTFILES/devtools
fi

if [[ -f "$DOTFILES/zsh/zsh_devtools" ]]; then
    source $DOTFILES/zsh/zsh_devtools
fi

if [[ -f "$DOTFILES/zsh/zsh_paths" ]]; then
    source $DOTFILES/zsh/zsh_paths
fi

if [[ -f "$DOTFILES/zsh/zsh_options" ]]; then
    source $DOTFILES/zsh/zsh_options
fi

if [[ -f "$DOTFILES/zsh/zsh_plugins" ]]; then
    source $DOTFILES/zsh/zsh_plugins
fi

if [[ -f "$HOME/.zshrc.local" ]]; then
    source $HOME/.zshrc.local
fi

source $ZSH/oh-my-zsh.sh


if [[ -f "$DOTFILES/zsh/zsh_aliases" ]]; then
    source $DOTFILES/zsh/zsh_aliases
fi

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

