export DOTFILES=$HOME/.dotfiles
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="agnoster"
DEFAULT_USER=$USER

source $DOTFILES/zsh/zsh_options
source $DOTFILES/devtools
source $DOTFILES/zsh/zsh_devtools
source $DOTFILES/zsh/zsh_paths
source $DOTFILES/zsh/zsh_plugins
[[ -f $HOME/.zshrc.local ]] && source $HOME/.zshrc.local

[[ -d $HOME/.docker/completions ]] && fpath=($HOME/.docker/completions $fpath)
source $ZSH/oh-my-zsh.sh

source $DOTFILES/zsh/zsh_prompt
source $DOTFILES/zsh/zsh_aliases

export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"
