#!/bin/bash

# bash_profile

load_dotfiles() {
    declare -a files=(
        $HOME/.dotfiles/bash/bash_options     # Options
        $HOME/.dotfiles/bash/bash_exports     # Exports
        $HOME/.dotfiles/bash/bash_aliases     # Aliases
        $HOME/.dotfiles/bash/bash_functions   # Functions
        $HOME/.dotfiles/bash/bash_prompt      # Custom bash prompt
        $HOME/.bash_profile.local             # Local and private settings not under version control (e.g. git credentials)
        $HOME/.dotfiles/bash/bash_paths       # Path modifications (must source after `.bash_profile.local` in case of custom `brew` location)
    )

    # if these files are readable, source them
    for index in ${!files[*]}
    do
        if [[ -r ${files[$index]} ]]; then
            source ${files[$index]}
        fi
    done
}

# source Bash completion (installed via Homebrew)
# only use `brew` after it has been added to the PATH
if [[ -r $(brew --prefix)/etc/bash_completion ]]; then
    source $(brew --prefix)/etc/bash_completion
fi

source $HOME/.devtools
# set 256 color profile where possible
if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
    export TERM=xterm-256color
fi

load_dotfiles
unset load_dotfiles

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="${HOME}/.sdkman"
[[ -s "${HOME}/.sdkman/bin/sdkman-init.sh" ]] && source "${HOME}/.sdkman/bin/sdkman-init.sh"

