#!/bin/bash

# bash_profile

load_dotfiles() {
    declare -a files=(
        $HOME/.dotfiles/bash/bash_options     # Options
        $HOME/.dotfiles/bash/bash_exports     # Exports
        $HOME/.dotfiles/bash/bash_aliases     # Aliases
        $HOME/.dotfiles/bash/bash_functions   # Functions
        $HOME/.dotfiles/bash/bash_prompt      # Custom bash prompt
        $HOME/.bash_profile.local             # Local and private settings not under version control (e.g. git credentials)
        $HOME/.dotfiles/bash/bash_paths       # Path modifications (must source after `.bash_profile.local` in case of custom `brew` location)
    )

    #        /usr/local/share/chruby/chruby.sh     # Enable postmodern/chruby
    #        /usr/local/share/chruby/auto.sh       # Enable autoswitching of rubies
    #        /usr/local/share/gem_home/gem_home.sh # Support changing $GEM_HOME


    # if these files are readable, source them
    for index in ${!files[*]}
    do
        if [[ -r ${files[$index]} ]]; then
            source ${files[$index]}
        fi
    done
}

# source Bash completion (installed via Homebrew)
# only use `brew` after it has been added to the PATH
if [[ -r $(brew --prefix)/etc/bash_completion ]]; then
    source $(brew --prefix)/etc/bash_completion
fi

source $HOME/.devtools
# set 256 color profile where possible
if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
    export TERM=xterm-256color
fi

load_dotfiles
unset load_dotfiles

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
# added by Miniconda2 4.7.12 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '${HOME}/opt/miniconda2/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "${HOME}/opt/miniconda2/etc/profile.d/conda.sh" ]; then
# . "/Users/mark/opt/miniconda2/etc/profile.d/conda.sh"  # commented out by conda initialize
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="${HOME}/opt/miniconda2/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda init <<<

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="${HOME}/.sdkman"
[[ -s "${HOME}/.sdkman/bin/sdkman-init.sh" ]] && source "${HOME}/.sdkman/bin/sdkman-init.sh"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/opt/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/opt/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

