#!/bin/bash

# bash_aliases

# Allow aliases to be with sudo
alias sudo="sudo "

# Easier navigation: .., ..., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ~="cd ~"
alias -- -="cd -"

alias m1st="mvn install -T1C -DskipTests"
alias m1cst="mvn clean install -T1C -DskipTests"
alias m1c="mvn clean install -T1C"
alias m1="mvn install -T1C"

alias bi="bundle install"
alias bu="bundle update"
alias be="bundle exec"

alias gp="git pull"
alias gfu="git fetch upstream"
alias gru="git rebase upstream/master"
alias gmu="git merge upstream/master"
alias tower="gittower ."

alias cass="cd ${HOME}/git/spring-data-cassandra"
alias redis="cd ${HOME}/git/spring-data-redis"
alias lettuce="cd ${HOME}/git/lettuce"
alias spinach="cd ${HOME}/git/spinach"

importprfunction() {
    curl -L ${1}.patch | git am --ignore-whitespace
}

alias importpr=importprfunction
alias cass-2="cd /Entwicklung/tools/apache-cassandra-2.2.5/bin"
alias cass-3="cd /Entwicklung/tools/apache-cassandra-3.7/bin"



# List dir contents aliases
# ref: http://ss64.com/osx/ls.html
# Long form no user group, color
alias l="ls -oG"
# Order by last modified, long form no user group, color
alias lt="ls -toG"
# List all except . and ..., color, mark file types, long form no user group, file size
alias la="ls -AGFoh"
# List all except . and ..., color, mark file types, long form no use group, order by last modified, file size
alias lat="ls -AGFoth"

# Concatenate and print content of files (add line numbers)
alias catn="cat -n"

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en1"

# Copy my public key to the pasteboard
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | printf '=> Public key copied to pasteboard.\n'"

# Flush DNS cache
alias flushdns="dscacheutil -flushcache"

# Empty the Trash on all mounted volumes and the main HDD
# Also, clear Apple’s System Logs to improve shell startup speed
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

# Show/hide hidden files in Finder
alias showdotfiles="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidedotfiles="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting)
alias showdeskicons="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
alias hidedeskicons="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
