#!/bin/bash

# bash_config

export DISABLE_AUTO_TITLE=true

# Make mate the default editor
export EDITOR="mate -w"

# Make mate the default Git editor and place caret at Line 1
export GIT_EDITOR="mate -wl1"

# Ignore commands that start with spaces and duplicates
export HISTCONTROL=ignoreboth

# Increase the maximum number of commands to remember
# (default is 500)
export HISTSIZE=32768

# Increase the maximum number of lines contained in the history file
# (default is 500)
export HISTFILESIZE=$HISTSIZE

# Make some commands not show up in history
export HISTIGNORE="ls:ls *:cd:cd -:pwd;exit:date:* --help"

# Don't clear the screen after quitting a manual page
export MANPAGER="less -X"

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# Always enable colored `grep` output
export GREP_OPTIONS="--color=auto";

# Maven Options
export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=512m"
export M2_REPO=$HOME/.m2/repository/

# Java Home
export JAVA_HOME=$(/usr/libexec/java_home -v 1.7)
export M2_HOME=$DEVTOOLS_HOME/apache-maven-$MAVEN_VERSION
export MAVEN_HOME=$DEVTOOLS_HOME/apache-maven-$MAVEN_VERSION


