#!/bin/bash

# bashrc
[ -n "$PS1" ] && source ~/.bash_profile

# added by travis gem
[ -f /Users/mark/.travis/travis.sh ] && source /Users/mark/.travis/travis.sh

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
