#!/bin/bash

source "$HOME/.devtools"

if [[ -r $(brew --prefix)/etc/bash_completion ]]; then
    source "$(brew --prefix)/etc/bash_completion"
fi

for file in bash_options bash_exports bash_aliases bash_functions; do
    source "$HOME/.dotfiles/bash/$file"
done
unset file

[[ -r $HOME/.bash_profile.local ]] && source "$HOME/.bash_profile.local"
source "$HOME/.dotfiles/bash/bash_paths"

export SDKMAN_DIR="$HOME/.sdkman"
(( BASH_VERSINFO[0] >= 4 )) && [[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"
