#!/bin/bash

cleanup() {
    local q="${1:-*.DS_Store}"
    find . -type f -name "$q" -ls -delete
}

qh() {
    cat ~/.bash_history | grep --color=always "$*" | less -RX
}

qt() {
    grep -ir --color=always "$*" . | less -RX
}
